### ISSUE TITLE
Password validation for registration.

### ISSUE THREAD

**Issue by dhruvik1999** [named-data-mobile/ndn-photo-app#108]
before there is no special code for validating username and password.

rules for password validation:- 

1)         The password should be less than 15 and more than 8 characters in length.
2)         The password Should not be same as username.
3)         The password should contain atleast one number.
4)         The password should contain atleast one special character.

username validation:-

1)        The number of characters must be between 6 to 15.

**Comment by jrandallclark** [comment]
The password the user enters is not currently used anywhere in the app and sers may never create a password in the final version. I don't think it is worth the trouble to add this right now.

**Comment by dhruvik1999** [comment]
I am planning to add the logout button also.
for example: If any wrong person takes our mobile then they should not able to use this application.

**Comment by jrandallclark** [comment]
User logout is not currently something we can support. See more: https://github.com/named-data-mobile/ndn-photo-app/pull/19#issuecomment-469764456

**Comment by dhruvik1999** [comment]
okay, i understand.
but still, I had done this part, if you find that correct then merge it.
pr : #110
