### ISSUE TITLE
Does not Build: Execution failed for task ':app:lintVitalRelease

### ISSUE THREAD

**Issue by josharsh** [named-data-mobile/ndn-photo-app#116]
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve com.android.support.test:runner:1.0.2.
     Required by:
         project :app
      > Could not resolve com.android.support.test:runner:1.0.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/support/test/runner/1.0.2/runner-1.0.2.jar'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/support/test/runner/1.0.2/runner-1.0.2.jar'.
               > Read timed out

**Comment by jrandallclark** [comment]
Can you post a more detailed log as shown here: https://stackoverflow.com/a/53669619 ?

**Comment by josharsh** [comment]
Will do

Thanks
