### ISSUE TITLE
App crashes after the Registration screen

### ISSUE THREAD

**Issue by aadhitya98** [named-data-mobile/ndn-photo-app#136]
After cloning the app from Git, I built the gradle in android studio and executed the app in my phone. After the registration, the app kept on popping..."App keeps Closing"

I also ensured that the NDN server is running and Wifi Direct was also available.

**Comment by agawande** [comment]
Please upload/paste the logs you see in the Android Studio.

**Comment by aadhitya98** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/38691254/54827825-df07fb80-4cd8-11e9-838e-cc4e2b95cca4.png)

This is what I am getting when running the app on my phone.

**Comment by zedlabs** [comment]
i was getting the same because the image being returned to the OnActivityResult in the mainActivity was null, #96 fixed it for me.

**Comment by jrandallclark** [comment]
@aadhitya98 I have merged zedlabs' changes. Please try the newest version and let us know if you still have this problem.
