### ISSUE TITLE
Registration Failing For First Time

### ISSUE THREAD

**Issue by guy34code** [named-data-mobile/ndn-photo-app#141]
**Summary:** 

The App shows Register Failed for : /username when registering for the first time.

**Steps to reproduce:** 

Fill the details(username and password) and click Register.

**System logs:**

```
E/Producer: Register failed for: /npChat/hello
I/Node: Register prefix failed: Error sending the register prefix interest to the forwarder: {0}

E/Producer: Register failed for: /npChat/sync
D/onCreate: Globals face is null?: false; Globals security is setup: true

```

**Device and Android version:** 

Model: Xiaomi MiA1
Android version: Android 9.0 Pie
ROM: Stock ROM

**Screen-shots:** 

![WhatsApp Image 2019-03-26 at 1 20 42 AM](https://user-images.githubusercontent.com/34396777/54949644-88632180-4f65-11e9-8a4b-05164282bdb3.jpeg)

**Would you like to work on the issue?**

I would like to work on this issue.

**Comment by dev-ritik** [comment]
@guy34code please confirm that you have [NFD](https://play.google.com/store/apps/details?id=net.named_data.nfd) app installed in the device and NFD was active.

**Comment by guy34code** [comment]
@dev-ritik  Yes, NFD app was Installed and running in background. I even tried it again multiple times, but it shows registration Failed.

**Comment by guy34code** [comment]
@dev-ritik I figured it out, the problem was with my College Wifi proxy settings. It worked on other wifi and mobile data.
