### ISSUE TITLE
 Move face.processEvents to a service

### ISSUE THREAD

**Issue by jrandallclark** [named-data-mobile/ndn-photo-app#145]
The thread "networkThread" constantly calls face.processEvents while the app is running. This should be moved to a service.

https://redmine.named-data.net/issues/4898

**Comment by neel1998** [comment]
@jrandallclark i would like to work on this one.

**Comment by neel1998** [comment]
@jrandallclark  can you please elaborate on this issue

**Comment by jrandallclark** [comment]
After looking into this some more, I'm not sure if it's necessary. I posted the issue after reading an old comment from a previous developer. 

Since the npChat protocol requires both users to be running the app in order to sync, keeping this as-is is probably for the best.

**Comment by neel1998** [comment]
@jrandallclark alright. Still if you find anything which requires fixing this, do let me know.. i will also check once myself. Meanwhile I will be focusing on shared preferences issue, since there is also lot work to be done
