### ISSUE TITLE
Use jNDN SegmentFetcher with AIMD pipelining to fetch the photos/files

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#147]
**Summary:** 
Use jNDN SegmentFetcher with AIMD pipelining to fetch the photos/files

**Would you like to work on the issue?**
yes.
@agawande  Can you please guide me how should I start working on this issue.

**Comment by agawande** [comment]
Initial pull request has been already made:
https://github.com/named-data/jndn/pull/24/

**Comment by dev-ritik** [comment]
@neel1998 ,I think you should take up some other new issue as I have made significant progress wrt updating the library and using it in the app. @agawande what's your opinion on this?

**Comment by agawande** [comment]
Yes, you can continue working on the jNDN pull request as considerable progress has already been made.

**Comment by neel1998** [comment]
Sorry @dev-ritik  I wasn't aware you were already working on this issue.
