### ISSUE TITLE
in settings activity old profile pic and change button should be at the center of the screen

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#16]
Currently old profile pic and change button are aligned to top left corner which doesn't look good.

![screenshot_20190303-224918](https://user-images.githubusercontent.com/32041242/53698733-c0fc5900-3e06-11e9-8a24-79f810b47bed.png)

**Comment by iamvasuh** [comment]
i would like to work on this issue @agawande

**Comment by neel1998** [comment]
@iamvasuh  i am already working on this one. Sorry

**Comment by iamvasuh** [comment]
> @iamvasuh i am already working on this one. Sorry

can i work on other one ?

**Comment by neel1998** [comment]
Sorry @iamvasuh I am about to submit PRs for most the issues opened by me in an hour.
