### ISSUE TITLE
Sign Up activity exist but not accessible and commented out

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#17]
Sign up activity should be made available so that user can make new account . @agawande  kindly review this issue. I think this needs to be implemented and i would like to work on it

**Comment by neel1998** [comment]
@agawande @jrandallclark  can you please look into this issue...thanks

**Comment by jrandallclark** [comment]
The SignUp activity is not currently part of the app. Users register their name in the initial login activity.
