### ISSUE TITLE
Broken boost library package for android-crew

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#176]
**Summary:** 

The latest version of boost library on https://github.com/named-data-mobile/android-crew-staging/releases 1.70.0 seems broken. Extracting it is giving error. 

And hence the following command is failing,

``` CREW_OWNER=named-data-mobile crew.dir/crew install target/boost target/ndn_cxx ```

The earlier version 1.68.0 is working fine.

**Would you like to work on the issue?**
@jrandallclark please check, I am not sure whether this is a correct place to submit this issue. But is is essential to resolve since it might prevent new contributors to set up the android project.

**Comment by jrandallclark** [comment]
I'm not having this issue on my system. Are you trying to build NFD Android or PSync?

**Comment by neel1998** [comment]
I was running the command
``` CREW_OWNER=named-data-mobile crew.dir/crew install target/boost target/ndn_cxx ```
And while that it tried to install the 1.70.0 version of boost and it couldn't extract it.

**Comment by jrandallclark** [comment]
I'll test this more thoroughly myself later today or tomorrow. If this is an problem, I'll contact the administrator of the crew staging repo since it doesn't seem that they accept issues.

**Comment by neel1998** [comment]
Great. Because i directly downloaded the tar.xz file for boost 1.70.0 and tried extracting it but it failed.

**Comment by jrandallclark** [comment]
![Screenshot_2020-02-19_15-36-21](https://user-images.githubusercontent.com/46690018/74878972-d1feec80-532d-11ea-9203-737ec02bc88a.png)

That's odd. I'm not having that problem.

**Comment by neel1998** [comment]
Maybe then it was some issue with my OS. Closing this issue. Thanks.
