### ISSUE TITLE
Make orientation of QR code scanner activity portrait

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#178]
**Summary:** 
Currently the QR code scanner is opening in only landscape mode, which is quite in convenient since rest of the app is working in portrait mode. 

**Steps to reproduce:** 
Open QR code scanner, from adding friend activity

**Would you like to work on the issue?**
Yes

**Comment by jrandallclark** [comment]
This would be an improvement.

**Comment by neel1998** [comment]
Will make a PR for this soon
