### ISSUE TITLE
User Logging function on main thread

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#25]
Currently user logging is happening on main thread which is not good practice. There should be an Async Task for user log in. Implementing an async task will also help showing a progressbar while user is loggin in to enhance UX. @agawande @jrandallclark  kindly share your thoughts on this issue. I think we need an Async Task for log in

**Comment by neel1998** [comment]
@agawande @jrandallclark  can you please look into this issue...thanks

**Comment by agawande** [comment]
Yes, this sounds nice. Definitely there is lag when logging in.

**Comment by neel1998** [comment]
@agawande  okay..I will make the changes and file the PR

**Comment by neel1998** [comment]
@agawande  @jrandallclark  I have made the PR to make the login function async. However there is still some lag when logging in. Which i assume is caused by the Filemanager class, which creates directories and files when logging in. I don't see any advantage of creating so many files. Cant't we store all the data in shred preferences. That would be fast and also better in code design aspects then creating seperate files.

Kindly share your view. I think this issue needs to be solved.

**Comment by jrandallclark** [comment]
I can see the benefits of replacing the username and friends' usernames files by using SharedPreferences, but don't see what else we would use it for.

Additionally, the login page is really a registration page and is only used the first time a user opens the app, so a small bit of lag while we initially set things up isn't a dealbreaker for me.

**Comment by neel1998** [comment]
@jrandallclark  it is not just about login where shared preferences will be used, currently to bring the friends list, remove friends , photos list and all is also done using FileManager only. I really don't find it appropriate. Even for the long term goals having shared preferences would make it really easy to handle data since , we can store and access data as JSON using tools like GSon . 

I do find it important to have shared prefs. Still I am open to suggestions by you and other mentors.

Thanks

**Comment by jrandallclark** [comment]
Ok. I will look into it further. You should create a new issue for the FileManager activity as this issue will close when I merge your pull request.

**Comment by neel1998** [comment]
@jrandallclark  Okay, i will create new issue regarding this. Thanks
