### ISSUE TITLE
Proposal for new App design

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#26]
Currently the theme and design of the app uses too much bright colors which doesnt look good. I suppose we should aim for minimilastic design approach. Following is the mockup of the home screen made by me. I think such design would look much better than the current one .

If the maintainers agree. I would like to change the design of he entire app to make it publishable.

@agawande  @jrandallclark  kindly look at this design please. and share your thoughts

![home](https://user-images.githubusercontent.com/32041242/53702777-b22a9c00-3e30-11e9-9fda-f8609fbe0ba7.png)

**Comment by neel1998** [comment]
@agawande @jrandallclark  can you please look into this issue...thanks

**Comment by agawande** [comment]
Apart from more pleasing to the eyes, what are the other advantages of this minimal design? imo the white space reduces the clickable surface of the big buttons.

**Comment by neel1998** [comment]
@agawande  i didn't get your point exactly..Can you please elaborate?
