### ISSUE TITLE
Changes to Wording and Alignment

### ISSUE THREAD

**Issue by AB261** [named-data-mobile/ndn-photo-app#27]
In the dashboard there is an option called see photos. I think a better word would be "Gallery" further the padding given to the profile photo on the taskbar is much different than the padding given to the dashboard images. These need to be uniform. 

![screenshot_20190304-105054](https://user-images.githubusercontent.com/17261046/53712164-adcfa480-3e6b-11e9-9a53-c7d27559db03.jpg)

I would like to fix this

**Comment by neel1998** [comment]
@AB261 The profile picture padding issue is already solved and merged..Kindly check the closed issues and PR once

**Comment by jrandallclark** [comment]
"See Photos" is for photos you have received from your friends. Photos are automatically deleted a few seconds after being viewed like in Snapchat, so I don't think Gallery is a good title.
