### ISSUE TITLE
[BUG] No clicklister for login button in LoginActivity

### ISSUE THREAD

**Issue by Cool-fire** [named-data-mobile/ndn-photo-app#34]
### Describe the Bug
There is no onclicklistener for login button in Login Activity.
### Expected Behaviour
There should be a onClicklistener for login button in login activity so that users can click on button to navigate to main activity on succesfull login.

**Comment by jrandallclark** [comment]
I don't understand the issue here. "onClick" is implemented for the login button in activity_login.xml and the login button works. There is no need to use an onClickListener in the actual code itself.
