### ISSUE TITLE
Add a back button in all the toolbars

### ISSUE THREAD

**Issue by shiv07tiwari** [named-data-mobile/ndn-photo-app#46]
During activity transition, as per the material design , we need to add back buttons in all the activities that have a parent activity.
![image](https://user-images.githubusercontent.com/38163725/53847967-b1cd0500-3fd8-11e9-8a03-d5bc878a4994.png)

**Comment by shiv07tiwari** [comment]
@agawande @jrandallclark Should I add this ?

**Comment by jrandallclark** [comment]
Activities should not have back buttons as the Android OS already provides one. Ref: https://developer.android.com/training/implementing-navigation/temporal
