### ISSUE TITLE
Empty data place holder for Photos and Friends Activity

### ISSUE THREAD

**Issue by shiv07tiwari** [named-data-mobile/ndn-photo-app#49]
Right now when we dont have any friends or photos, the screen just shows a text saying nothing to display, which looks bad.
Maybe we can add a placeholder to display no data. This follows the material design guidelines.
![image](https://user-images.githubusercontent.com/38163725/53848357-f86f2f00-3fd9-11e9-901d-9e1e63a0cbf3.png)
Somewhat similar to this.

**Comment by shiv07tiwari** [comment]
@agawande @jrandallclark  Should I add this ?

**Comment by jrandallclark** [comment]
This is a good idea, but the app's current design is just a placeholder, so any major changes are probably not worth your time.

**Comment by shiv07tiwari** [comment]
@jrandallclark Yes, so basically I guess adding the place holders right now is a good idea so as to make a proper place holder app, and then start working on the actual concept.
Shall I start ?
