### ISSUE TITLE
Remove reluctant casting in various places of code

### ISSUE THREAD

**Issue by shiv07tiwari** [named-data-mobile/ndn-photo-app#53]
In the AndroidStudio code, we have various reluctant castings performed. This should be removed as per AndroidStudio guidelines, because it is useless and decreases coding standards.

**Comment by jrandallclark** [comment]
Good catch. I had noticed this, too. I will test your changes later today to ensure there wasn't a reason the code was written this way before.

**Comment by shiv07tiwari** [comment]
@jrandallclark Okay Thanks.
