### ISSUE TITLE
Feedback - for every user to suggest changes to the developers 

### ISSUE THREAD

**Issue by HemanthReddy99** [named-data-mobile/ndn-photo-app#62]
I believe every user would like to review and suggest further improvements in the app, hence making it vital for them to contact the developers.
The feedback option can help with this.
I've already got everything ready to submit a pull request, just waiting for your opinions.
@agawande @jrandallclark please, look into this.
Thanks.

**Comment by jrandallclark** [comment]
I am not sure this is a standard feature of Android apps, especially one being created for research purposes.
