### ISSUE TITLE
Replace FileManager with Shared Preferences for better code design and ease to access data

### ISSUE THREAD

**Issue by neel1998** [named-data-mobile/ndn-photo-app#63]
Currently new files are created each time user tries to add new data or access some data. Instead there should be shared preferences to handle data for better code design

(@jrandallclark  is still looking into this issue . Once mentors finalize the need for this issue I will start working on this issue)

**Comment by neel1998** [comment]
@jrandallclark  any updates on this issue?

**Comment by neel1998** [comment]
@jrandallclark  I need some guidance for this issue. Since there are lot files created for friends lists, credentials, QR codes etc. Should we convert them all to shared preference. For now I will convert credential files to shared preferences . So login will be completely working with shared preferences. IF you find that correct, we can go ahead for other files as well

**Comment by jrandallclark** [comment]
Initially, I think simple data that is already stored as integers, strings, etc. can be switched over to using SharedPreferences. 

So, I would start by adding things like the user name and friends list to SharedPreferences. Friend keys are stored as text files on the phone's storage and can be added as well.

We can keep saving the QR codes as images for now until we decide what exactly we want to do with them.

**Comment by neel1998** [comment]
@jrandallclark  thanks for the clarification . Kindly check the PR i just made. If you are fine with the changes I will add other functionalities like friends list and friends key as well to shared preferences
