### ISSUE TITLE
Warning due to missing height in toolbar landscape mode

### ISSUE THREAD

**Issue by shiv07tiwari** [named-data-mobile/ndn-photo-app#69]
In include section of toolbar in landscape mode, it gives a minor issue due to missing height attribute.

**Comment by neel1998** [comment]
I think this issue has been already solved by @somenath1435  and also made a PR. Kindly check and close this one.

**Comment by shiv07tiwari** [comment]
@neel1998 That PR misses the error in landscape mode. This issue is for landscape mode which was not at all mentioned in the PR or issue.

**Comment by neel1998** [comment]
@shiv07tiwari  still both PR are making exactly same change. Check once your self. Also the height attribute is independent of portrait/landscape mode

**Comment by shiv07tiwari** [comment]
@neel1998 We have entirely different xml files for 2 modes. So we need to fix the warning in both the files.

**Comment by neel1998** [comment]
@shiv07tiwari  alright I might have missed something. I will che k once myself

**Comment by shiv07tiwari** [comment]
@neel1998 Okay
