### ISSUE TITLE
Make the images in toolbar circular 

### ISSUE THREAD

**Issue by shiv07tiwari** [named-data-mobile/ndn-photo-app#73]
@jrandallclark I think making the toolbar image a circularView image will drastically improve the looks of toolbar. So if we are not removing the image from the toolbar, maybe we can work towards improving the UI. Your thoughts ?
@agawande

**Comment by neel1998** [comment]
@shiv07tiwari  circular image may look good. But since entire UI of the app has to be changed later. This change is not required at this stage i guess

**Comment by shiv07tiwari** [comment]
@neel1998 As per @jrandallclark , minor UI fixes are allowed which might persist in future.

**Comment by neel1998** [comment]
@shiv07tiwari  alrightyy..File the PR .. let maintainers take decision . Cheers!!

**Comment by shiv07tiwari** [comment]
@neel1998 Instead of making a PR, i should first wait for the maintainers for their suggestion.
