### ISSUE TITLE
Implementation of LogIn.

### ISSUE THREAD

**Issue by shiv07tiwari** [named-data-mobile/ndn-photo-app#76]
@jrandallclark @agawande 
I observed that we have added a listener on password edit Text for the purpose of LogIn.
Is their any particular reason for same ?
If not, we should implement the function login after the user presses the login button, instead of adding a listener in the edit text field.
Please tell me if I am missing something.

**Comment by neel1998** [comment]
This has been added to enhance the user experience...When user enter the password , user can login using both keyboard enter and login button. Please close this issue

**Comment by shiv07tiwari** [comment]
@neel1998 Okay now I understood the reason. Thanks for informing

**Comment by neel1998** [comment]
@shiv07tiwari  no problem. You can close the issue
