### ISSUE TITLE
Add a progress bar in Login Screen

### ISSUE THREAD

**Issue by shiv07tiwari** [named-data-mobile/ndn-photo-app#77]
When a user logs in, due to implementation in AsyncTask, their is a time until when the user is redirected to MainScreen, till then the button disappears and it kinds of freezes. We should replace it with a progress bar.
![videotogif_2019 03 07_21 36 47](https://user-images.githubusercontent.com/38163725/53970948-d385d380-4121-11e9-98d2-054cf008a518.gif)

**Comment by neel1998** [comment]
@shiv07tiwari  kindly check my PR for login change. I have added the progress bar . But the lag is bcz of the file creation. I have already asked maintainers for changing the login implementation. You can close this issue

**Comment by shiv07tiwari** [comment]
@neel1998 I noticed that ProgressBar is present but what I also noticed is that it is not at all visible with the current implementation, i fixed it. Kindly refer to my PR.
We will again refix if the maintainers agree to change the login implementation, but the issue is fixed for now. (It is a very minor change)

**Comment by neel1998** [comment]
I saw your change. For temporary functionality it is fine. But it is kind of a hack . But should work:)
