### ISSUE TITLE
Add Exit alert dialog in Mainactivity

### ISSUE THREAD

**Issue by somenath1435** [named-data-mobile/ndn-photo-app#87]

**Comment by neel1998** [comment]
@somenath1435  @jrandallclark  is this really needed? I don't see any advantage of it in our app design. If there are chances of user accidentally pressing back button, then this could have been useful. Currently sich alert would decrease UX rather than improving

**Comment by jrandallclark** [comment]
I agree. As a user, I would find this obtrusive.

**Comment by somenath1435** [comment]
@neel1998 @jrandallclark I think it will be useful since user should be notified that pressing back will terminate the activity.Displaying alert should help
