### ISSUE TITLE
updated login activity UI.

### ISSUE THREAD

**Issue by dhruvik1999** [named-data-mobile/ndn-photo-app#94]
please refer to #93 

I propose to change the UI of login activity.
1. EditText of username and password field updated with round _edit_text.
2. username and password textView removed.
3. place of entire

Preview
After
![screenshot_2019-03-08-18-57-06-845_memphis myapplication](https://user-images.githubusercontent.com/32356700/54032553-fc68a000-41d7-11e9-8c93-9120aa4a99e2.png)

before
![screenshot_2019-03-08-18-30-57-507_memphis myapplication](https://user-images.githubusercontent.com/32356700/54032562-038fae00-41d8-11e9-96cd-e0ea5ddf83bb.png)

**Comment by jrandallclark** [comment]
This is a better look, but as the current UI is just a placeholder until we revamp it entirely, I don't think it is worth the trouble to make major changes to individual activities.
