### ISSUE TITLE
Tapping on Friends in FriendList should allow the user to send photo to this friend.

### ISSUE THREAD

**Issue by vgveerain** [named-data-mobile/ndn-photo-app#98]
Apparently, the FriendList in View Friends is unresponsive and is redundant UX as it simply doesn't do anything. It should, in theory, allow the user to send a photo to a friend if the user taps on a friend. I would like to add this option. @agawande @jrandallclark, what are your opinions on this?

**Comment by zedlabs** [comment]
@vgveerain currently the only way to share the images is through the camera, this is not the final UI

**Comment by vgveerain** [comment]
Even when the UI is changed, the code will be relevant as it would simply be a matter of applying the onclick listener to a different view. Unless you're suggesting that the whole idea of viewing friend list is removed.

**Comment by dev-ritik** [comment]
Using the FriendList to send data to a particular user will involve much more than changes in views and listeners. Issues like [this](https://redmine.named-data.net/issues/4753) needs to be handled before working on this one.
